### ISSUE TITLE
Paginator Buttons/Reactions Not Appearing in Message Despite No Errors

### ISSUE THREAD

**Issue by Paillat-dev** [FasterSpeeding/Yuyo#496]
## Description

When implementing a paginator using the `yuyo.ComponentPaginator`, no errors are thrown, and the interaction is responded to correctly. However, the message does not contain any paginator buttons or reactions.

## Code Sample

Here's the code snippet for the paginator:

```py
paginator = yuyo.ComponentPaginator(paginatorIter)
first_page = await paginator.get_next_entry()
assert first_page, "get_next_entry shouldn't ever return None here as we already know the amount of pages"
message = await ctx.edit_initial_response(**first_page.to_kwargs())
component_client.register_executor(paginator, message=message)
```

And for initializing the bot and component client:

```py
bot = hikari.RESTBot(
    token=os.getenv("TOKEN"),
    token_type=hikari.TokenType.BOT,
    public_key=os.getenv("PUBLIC_KEY"),
)
component_client: yuyo.ComponentClient = yuyo.ComponentClient.from_rest_bot(bot)
```

## Expected Behavior

I expect the message to have paginator buttons or reactions that allow users to navigate through the paginated content.

## Actual Behavior

The message appears, but it lacks paginator buttons or reactions.

## Steps to Reproduce

1. Initialize `hikari.RESTBot` and `yuyo.ComponentClient`.
2. Create a paginator instance with `yuyo.ComponentPaginator`.
3. Register the paginator executor.
4. Observe that the message lacks paginator buttons or reactions.

## Environment

- Python Version: Python 3.11.4
- `hikari` Version: 2.0.0.dev120
- `yuyo` Version: 1.19.0
- Operating System: Win 11 64

## Additional Information

- No error logs.
- The interaction is responded to correctly.
- Using a rest bot

**Comment by Paillat-dev** [comment]
## Issue Update:

The issue has been fixed. The root of the problem was found in `**first_page.to_kwargs()` not returning `components = self.rows`.

## Fix Explanation:

Upon further investigation, it appears that `**first_page.to_kwargs()` does not include `components = self.rows`. This leads to the absence of paginator buttons or reactions on the message.

## Proposed Changes:

I'll see if I can open a Pull Request to fix this behavior in the library.

## Workaround:

A temporary workaround is to explicitly set `components=paginator.rows` when editing the initial response. 

## Code Changes:

Additionally, I've made some other updates to the code, including:

- Setting triggers to an empty list to avoid defaults.
- Setting custom triggers with custom styles.

Here is the updated code snippet:

```py
paginator = (
    yuyo.ComponentPaginator(
        paginatorIter,
        triggers=[]
    )
    .add_first_button(
        style=hikari.ButtonStyle.PRIMARY, emoji=hikari.UNDEFINED, label="<<"
    )
    .add_previous_button(
        style=hikari.ButtonStyle.DANGER, emoji=hikari.UNDEFINED, label="<"
    )
    .add_next_button(
        style=hikari.ButtonStyle.SUCCESS, emoji=hikari.UNDEFINED, label=">"
    )
    .add_last_button(
        style=hikari.ButtonStyle.PRIMARY, emoji=hikari.UNDEFINED, label=">>"
    )
)
first_page = await paginator.get_next_entry()
assert (
    first_page
), "get_next_entry shouldn't ever return None here as we already know the amount of pages"
message = await ctx.edit_initial_response(
    **first_page.to_kwargs(), components=paginator.rows
)
component_client.register_executor(paginator, message=message)
```

**Comment by FasterSpeeding** [comment]
`to_kwargs()` isn't intended to include the components for you since this is just the data being returned by the iterator. They should be passed to the create/edit message method separately as your current code is doing.

**Comment by Paillat-dev** [comment]
> `to_kwargs()` isn't intended to include the components for you since this is just the data being returned by the iterator. They should be passed to the create/edit message method separately as your current code is doing.

That's also what I tougth. But in that case the example in the code should be change, I assume?

**Comment by Paillat-dev** [comment]
Oh just saw you did. Well then Ill close this
